version: 2
jobs:
  build:
    working_directory: /go/src/github.com/gjbae1212/grpc-vpn
    branches:
      only:
        - master
    docker:
      - image: golang:1.14
    environment:
      GOPATH: /go
    steps:
      - checkout
      - run:
          name: RUN UNIT TEST
          environment:
            GO111MODULE: "on"
          command: bash script.sh test
